# Generated by Django 3.2.10 on 2021-12-11 22:17

from django.db import migrations, models
import django.db.models.deletion
import jobs.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_name', models.CharField(max_length=200)),
                ('resume_file', models.FileField(upload_to=jobs.models._upload_path)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('apply_date', models.DateField()),
                ('apply_platform', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('phone', 'Phone Interview'), ('technical', 'Technical Interview'), ('offer', 'Offer'), ('rejected', 'Applied'), ('applied', 'Applied')], max_length=200)),
                ('job_post', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
