# Generated by Django 3.2.10 on 2021-12-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Phone Interview', 'Phone Interview'), ('Technical Interview', 'Technical Interview'), ('Offer', 'Offer'), ('rejected', 'Rejected')], max_length=200),
        ),
    ]
