# Generated by Django 3.2.10 on 2021-12-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Phone Interview', 'Phone Interview'), ('Technical Interview', 'Technical Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], max_length=200),
        ),
    ]
